# Lab 4
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/marts-dev/geog510-test/blob/main/lab4.ipynb)


## Exercise 1: Variable Assignment and Basic Operations
Create variables to store the following geospatial data:
- The latitude and longitude of New York City: 40.7128, -74.0060
- The population of New York City: 8,336,817
- The area of New York City in square kilometers: 783.8

Perform the following tasks:
1. Calculate and print the population of New York City(population per square kilometer).
2. Print the coordinates in the format "Latitude: [latitude], Longitude: [longitude]".

In [8]:
latitude = 40.7128
longitude = -74.0060
population = 8_336_817
area = 783.8
density = population / area
print(f"Population density of New York City is {density:.2f} people per square km")
print(f"Latitude: {latitude}, Longitude: {longitude}")

Population density of New York City is 10636.41 people per square km
Latitude: 40.7128, Longitude: -74.006


## Exercise 2: Working with Strings
Create a string variable to store the name of a city, such as "San Francisco". Perform the following operations:
1. Convert the string to lowercase and print the result
2. Convert the string to uppercase and print the result
3. Replace "San" with "Los" in the city name and print the new string

In [4]:
city_name = "San Francisco"
print(f"{city_name.lower()}")
print(f"{city_name.upper()}")
print(f"{city_name.replace('San', 'Los')}")

san francisco
SAN FRANCISCO
Los Francisco


## Exercise 3: Using Lists
Create a list of tuples, where each tuple contains the name of a city and its corresponding latitude and longitude:

- New York City: (40.7128, -74.0060)
- Los Angeles: (34.0522, -118.2437)
- Chicago: (41.8781, -87.6298)


Perform the following tasks:

1. Add a new city (e.g., Miami: (25.7617, -80.1918)) to the list.
2. Print the entire list of cities.
3. Slice the list to print only the first two cities.

In [5]:
cities_list  = [("New York City",(40.7128, -74.0060)), ("Los Angeles", (34.0522, -118.2437)), ("Chicago", (41.8781, -87.6298))]

cities_list.append(("San Francisco", (37.7749, -122.4194)))
print(cities_list)
print(cities_list[:2])

[('New York City', (40.7128, -74.006)), ('Los Angeles', (34.0522, -118.2437)), ('Chicago', (41.8781, -87.6298)), ('San Francisco', (37.7749, -122.4194))]
[('New York City', (40.7128, -74.006)), ('Los Angeles', (34.0522, -118.2437))]


## Exercise 4: Using Tuples
Create a tuple to store the coordinates (latitude, longitude) of the Eiffel Tower: (48.8584, 2.2945). Perform the following tasks:

1. Access and print the latitude and longitude values from the tuple.
2. Try to change the latitude value to 48.8585. What happens? Explain why.

In [6]:
eiffel_tower = (48.8584, 2.2945)
print(f"Eiffel Tower is located at latitude {eiffel_tower[0]} and longitude {eiffel_tower[1]}")
eiffel_tower[0] = 48.8585

Eiffel Tower is located at latitude 48.8584 and longitude 2.2945


TypeError: 'tuple' object does not support item assignment

The assignment throws an error because tuples are immutable in Python.

## Exercise 5: Working with Sets
Create a set of countries you have visited, such as {“USA”, “France”, “Germany”}. Perform the following tasks:

1. Add a new country to the set.
2. Try to add the same country again. What happens?
3. Print the updated set.

In [7]:
visited_countries = {"USA", "France", "Germany"}
# Task 1
visited_countries.add("Japan")
# Task 2: A dupplicate will not be added to the set
visited_countries.add("Japan")
# Task 3
print(visited_countries)

{'Germany', 'France', 'USA', 'Japan'}


## Exercise 6: Working with Dictionaries
Create a dictionary to store information about a specific geospatial feature, such as a river:

- Name: “Amazon River”
- Length: 6400 km
- Countries: [“Brazil”, “Peru”, “Colombia”]


Perform the following tasks:

1. Add a new key-value pair to the dictionary to store the river’s average discharge (e.g., 209,000 m³/s).
2. Update the length of the river to 6992 km.
3. Print the dictionary.

In [9]:
geo_features = {"Name": "Amazon River", "Length": 6400, "Countries": ["Brazil", "Peru", "Colombia"]}
print(f"Original dictionary: {geo_features}")
# Task 1
geo_features["Average Discharge"] = 209_000
# Task 2
geo_features["Length"] = 6992
# Task 3
print(f"Updated dictionary: {geo_features}")

Original dictionary: {'Name': 'Amazon River', 'Length': 6400, 'Countries': ['Brazil', 'Peru', 'Colombia']}
Updated dictionary: {'Name': 'Amazon River', 'Length': 6992, 'Countries': ['Brazil', 'Peru', 'Colombia'], 'Average Discharge': 209000}


## Exercise 7: Nested Data Structures
Create a dictionary to represent a city that contains the city’s name, population, and coordinates (latitude, longitude):

- Name: “Tokyo”
- Population: 13,515,271
- Coordinates: (35.6895, 139.6917)


Perform the following tasks:

1. Access and print the population of the city.
2. Access and print the city’s latitude.
3. Update the population to 14,000,000 and print the updated dictionary.

In [11]:
city_dict = {"Name": "Tokyo", "Population": 13_515_271, "Coordinates": (35.6895, 139.6917)}
# Task 1
print(f"Population: {city_dict['Population']}")
# Task 2
print(f"Latitude: {city_dict['Coordinates'][0]}")
# Task 3
city_dict["Population"] = 14_000_000
print(f"Updated dictionary: {city_dict}")

Population: 13515271
Latitude: 35.6895
Updated dictionary: {'Name': 'Tokyo', 'Population': 14000000, 'Coordinates': (35.6895, 139.6917)}


## Exercise 8: List Operations
Given the list of cities from Exercise 3, perform the following operations:

1. Sort the list of cities alphabetically by name.
2. Create a new list that contains only the city names.
3. Remove the last city from the original list and print the updated list.

In [12]:
# Task 1
cities_list.sort(key=lambda x: x[0])
print(cities_list)
# Task 2
new_list = [city[0] for city in cities_list]
print(new_list)
# Task 3
cities_list.pop(-1)
print(cities_list)

[('Chicago', (41.8781, -87.6298)), ('Los Angeles', (34.0522, -118.2437)), ('New York City', (40.7128, -74.006)), ('San Francisco', (37.7749, -122.4194))]
['Chicago', 'Los Angeles', 'New York City', 'San Francisco']
[('Chicago', (41.8781, -87.6298)), ('Los Angeles', (34.0522, -118.2437)), ('New York City', (40.7128, -74.006))]


## Exercise 9: Dictionary Operations
Using the dictionary from Exercise 6, perform the following tasks:

1. Check if the key “Length” exists in the dictionary.
2. Print all the keys in the dictionary.
3. Print all the values in the dictionary.

In [13]:
# Task 1
print("Length" in geo_features)
# Task 2
print(geo_features.keys())
# Task 3
print(geo_features.values())

True
dict_keys(['Name', 'Length', 'Countries', 'Average Discharge'])
dict_values(['Amazon River', 6992, ['Brazil', 'Peru', 'Colombia'], 209000])


## Exercise 10: Practical Application
Imagine you have a list of tuples, each representing a location with its name, latitude, and longitude:

```python
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475),
]
```
Perform the following tasks:

1. Create a new list that contains only the names of the locations.
2. Create a dictionary where the keys are location names and the values are tuples of their coordinates.
3. Print the latitude of “K2” using the dictionary.

In [14]:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475),
]
# Task 1
location_names = [location[0] for location in locations]
print(location_names)
# Task 2
location_dict = {location[0]: (location[1], location[2]) for location in locations}
print(location_dict)
# Task 3
print(f"Latitude of K2: {location_dict['K2'][0]}")

['Mount Everest', 'K2', 'Kangchenjunga']
{'Mount Everest': (27.9881, 86.925), 'K2': (35.8808, 76.5155), 'Kangchenjunga': (27.7025, 88.1475)}
Latitude of K2: 35.8808


## Exercise 11: Manipulating Geographic Location Strings

- Create a string that represents the name of a geographic feature (e.g., `"Amazon River"`).
- Convert the string to lowercase and then to uppercase.
- Concatenate the string with the name of the country (e.g., `"Brazil"`) to create a full location name.
- Repeat the string three times, separating each repetition with a dash (`-`).

In [2]:
# Task 1
geo_feat_name = "Amazon River"
# Task 2
print(geo_feat_name.lower())
print(geo_feat_name.upper())
# Task 3
geo_feat_name = geo_feat_name + ", Brazil"
# Task 4
for i in range(3):
  if i == 0:
    print(geo_feat_name, end="")
  else:
    print("-"+geo_feat_name, end="")

amazon river
AMAZON RIVER
Amazon River, Brazil-Amazon River, Brazil-Amazon River, Brazil

## Exercise 12: Extracting and Formatting Coordinates

- Given a string with the format `"latitude, longitude"` (e.g., `"40.7128N, 74.0060W"`), extract the numeric values of latitude and longitude.
- Convert these values to floats and remove the directional indicators (`N`, `S`, `E`, `W`).
- Format the coordinates into a `POINT` WKT string (e.g., `"POINT(-74.0060 40.7128)"`).

In [3]:
lat_long = "40.7128N, 74.0060W"
lat, lon = lat_long.split(", ")
fl_lat = float(lat[:-1])
fl_lon = float(lon[:-1])
print(f"POINT({fl_lat} {fl_lon})")

POINT(40.7128 74.006)


## Exercise 13: Building Dynamic SQL Queries

- Given a table name and a condition, dynamically build an SQL query string.
- Example: If `table_name = "cities"` and `condition = "population > 1000000"`, the query should be `"SELECT * FROM cities WHERE population > 1000000;"`.
- Add additional conditions dynamically, like `AND` clauses.

In [4]:
table_name = "cities"
condition = "population > 1000000"
additional_condition = ["AND country = 'USA'", "OR country = 'Canada'"]
query = f"SELECT * FROM {table_name} WHERE {condition} {' '.join(additional_condition)}"
print(query)

SELECT * FROM cities WHERE population > 1000000 AND country = 'USA' OR country = 'Canada'


## Exercise 14: String Normalization and Cleaning

- Given a list of city names with inconsistent formatting (e.g., `[" new york ", "Los ANGELES", "   CHICAGO"]`), normalize the names by:
  - Stripping any leading or trailing whitespace.
  - Converting them to title case (e.g., `"New York"`, `"Los Angeles"`, `"Chicago"`).
- Ensure that the output is a clean list of city names.

In [5]:
city_names = [" new york ", "Los ANGELES", "   CHICAGO"]

for i, city in enumerate(city_names):
  city_names[i] = city.title().strip()
print(city_names)

['New York', 'Los Angeles', 'Chicago']


## Exercise 15: Parsing and Extracting Address Information

- Given a string in the format `"Street, City, Country"` (e.g., `"123 Main St, Springfield, USA"`), write a function that parses the string into a dictionary with keys `street`, `city`, and `country`.
- The function should return a dictionary like `{"street": "123 Main St", "city": "Springfield", "country": "USA"}`.

In [7]:
def parse_address(address):
  address = address.split(", ")
  street = address[0]
  city = address[1]
  country = address[2]
  return {"street": street, "city": city, "country": country}

parse_address("123 Main St, Springfield, USA")

{'street': '123 Main St', 'city': 'Springfield', 'country': 'USA'}

## Exercise 16: Using For Loops to Process Coordinate Lists

- Create a list of tuples representing coordinates (latitude, longitude).
- Write a `for` loop that prints each coordinate and indicates whether it is in the Northern or Southern Hemisphere based on the latitude.

In [12]:
coords = [(40.7128, 74.0060), (-34.0522, 118.2437), (41.8781, 87.6298)]
for i, coord in enumerate(coords):
  lat, lon = coord
  if lat > 0 and lat <= 90:
    print(f"The latitude of {lat} is in the Northern Hemisphere")
  elif lat < 0 and lat >= -90.0:
    print(f"The latitude of {lat} is in the Southern Hemisphere")
  elif lat == 0:
    print(f"The latitude of {lat} is on the Equator")
  else:
    print(f"The latitude of {lat} is invalid")

The latitude of 40.7128 is in the Northern Hemisphere
The latitude of -34.0522 is in the Southern Hemisphere
The latitude of 41.8781 is in the Northern Hemisphere


## Exercise 17: While Loops for Iterative Processing

- Create a list of coordinates (latitude, longitude).
- Write a `while` loop that continues to print each coordinate until it encounters a coordinate with a negative latitude.
- Stop the loop once this condition is met.

In [13]:
coords = [(40.7128, 74.0060), (-34.0522, 118.2437), (41.8781, 87.6298)]
for i, coord in enumerate(coords):
  lat, lon = coord
  if lat < 0:
    print(f"The latitude of {lat} is in the Southern Hemisphere")
    break
  else:
    print(f"The latitude is {lat}")

The latitude is 40.7128
The latitude of -34.0522 is in the Southern Hemisphere


## Exercise 18: Conditional Logic in Loops

- Create a list of coordinates and use a `for` loop to iterate over them.
- Use an `if-elif-else` statement inside the loop to classify each coordinate based on its longitude:
  - Print `"Eastern Hemisphere"` if the longitude is greater than 0.
  - Print `"Western Hemisphere"` if the longitude is less than 0.

In [15]:
coords = [(40.7128, 74.0060), (-34.0522, 118.2437), (41.8781, -87.6298)]
for i, coord in enumerate(coords):
  lat, lon = coord
  if lon > 0 and lon <= 180:
    print(f"The longitude of {lon} is in the Eastern Hemisphere")
  elif lon < 0 and lon >= -180:
    print(f"The longitude of {lon} is in the Western Hemisphere")
  elif lon == 0:
    print(f"Prime Meridian")
  else:
    print(f"The longitude of {lon} is invalid")

The longitude of 74.006 is in the Eastern Hemisphere
The longitude of 118.2437 is in the Eastern Hemisphere
The longitude of -87.6298 is in the Western Hemisphere


## Exercise 19: Filtering Data with Combined Loops and Conditionals

- Given a list of coordinates, filter out and store only those located in the Southern Hemisphere (latitude < 0).
- Count the number of coordinates that meet this condition and print the result.

In [17]:
coords = [(40.7128, 74.0060), (-34.0522, 118.2437), (41.8781, 87.6298)]
southern_coords = []
for i, coord in enumerate(coords):
  lat, lon = coord
  if lat < 0:
    southern_coords.append(coord)

print(f"Number of Coordinates in Southern Hemisphere: {len(southern_coords)}")

Number of Coordinates in Southern Hemisphere: 1


## Exercise 20: Generating and Analyzing Random Coordinates

- Write a program that generates random coordinates (latitude between [-90, 90] degrees and longitude between [-180, 180] degrees).
- Use a `while` loop to keep generating coordinates until a pair with both latitude and longitude greater than 50 is generated.
- Print each generated coordinate and the final coordinate that meets the condition.

In [18]:
import random

def generate_coordinate():
  return (random.uniform(-90.0, 90.0), random.uniform(-180.0, 180.0))

while True:
  lat, lon = generate_coordinate()
  print(f"Latitude: {lat:.4f}, Longitude: {lon:.4f}")
  if lat > 50 and lon > 50:
    break;

Latitude: -34.7745, Longitude: -112.2493
Latitude: -53.9636, Longitude: -92.8747
Latitude: 30.8621, Longitude: 76.2693
Latitude: 51.8989, Longitude: 28.2993
Latitude: 7.9202, Longitude: 108.1979
Latitude: 0.3879, Longitude: 169.3693
Latitude: -13.3752, Longitude: -106.6072
Latitude: -8.0372, Longitude: 120.8267
Latitude: 64.8390, Longitude: 51.9915
